#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-rpart.plot
Version  : 3.1.1
Release  : 10
URL      : https://cran.r-project.org/src/contrib/rpart.plot_3.1.1.tar.gz
Source0  : https://cran.r-project.org/src/contrib/rpart.plot_3.1.1.tar.gz
Summary  : Plot 'rpart' Models: An Enhanced Version of 'plot.rpart'
Group    : Development/Tools
License  : GPL-3.0
BuildRequires : buildreq-R

%description
in the 'rpart' package.

%prep
%setup -q -c -n rpart.plot
cd %{_builddir}/rpart.plot

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1653343488

%install
export SOURCE_DATE_EPOCH=1653343488
rm -rf %{buildroot}
export LANG=C.UTF-8
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library rpart.plot
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -ftree-vectorize -mno-vzeroupper  " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --no-test-load --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library rpart.plot
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library rpart.plot
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc rpart.plot || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/rpart.plot/DESCRIPTION
/usr/lib64/R/library/rpart.plot/INDEX
/usr/lib64/R/library/rpart.plot/Meta/Rd.rds
/usr/lib64/R/library/rpart.plot/Meta/data.rds
/usr/lib64/R/library/rpart.plot/Meta/features.rds
/usr/lib64/R/library/rpart.plot/Meta/hsearch.rds
/usr/lib64/R/library/rpart.plot/Meta/links.rds
/usr/lib64/R/library/rpart.plot/Meta/nsInfo.rds
/usr/lib64/R/library/rpart.plot/Meta/package.rds
/usr/lib64/R/library/rpart.plot/NAMESPACE
/usr/lib64/R/library/rpart.plot/NEWS
/usr/lib64/R/library/rpart.plot/R/rpart.plot
/usr/lib64/R/library/rpart.plot/R/rpart.plot.rdb
/usr/lib64/R/library/rpart.plot/R/rpart.plot.rdx
/usr/lib64/R/library/rpart.plot/data/Rdata.rdb
/usr/lib64/R/library/rpart.plot/data/Rdata.rds
/usr/lib64/R/library/rpart.plot/data/Rdata.rdx
/usr/lib64/R/library/rpart.plot/doc/index.html
/usr/lib64/R/library/rpart.plot/doc/prp.pdf
/usr/lib64/R/library/rpart.plot/help/AnIndex
/usr/lib64/R/library/rpart.plot/help/aliases.rds
/usr/lib64/R/library/rpart.plot/help/paths.rds
/usr/lib64/R/library/rpart.plot/help/rpart.plot.rdb
/usr/lib64/R/library/rpart.plot/help/rpart.plot.rdx
/usr/lib64/R/library/rpart.plot/html/00Index.html
/usr/lib64/R/library/rpart.plot/html/R.css
/usr/lib64/R/library/rpart.plot/slowtests/README.txt
/usr/lib64/R/library/rpart.plot/slowtests/data.stagec
/usr/lib64/R/library/rpart.plot/slowtests/make.bat
/usr/lib64/R/library/rpart.plot/slowtests/makeclean.bat
/usr/lib64/R/library/rpart.plot/slowtests/rpart.report.R
/usr/lib64/R/library/rpart.plot/slowtests/rpart.report.Rout.save
/usr/lib64/R/library/rpart.plot/slowtests/rpart.report.bat
/usr/lib64/R/library/rpart.plot/slowtests/test.describe.col.R
/usr/lib64/R/library/rpart.plot/slowtests/test.describe.col.Rout.save
/usr/lib64/R/library/rpart.plot/slowtests/test.describe.col.bat
/usr/lib64/R/library/rpart.plot/slowtests/test.epilog.R
/usr/lib64/R/library/rpart.plot/slowtests/test.imports.R
/usr/lib64/R/library/rpart.plot/slowtests/test.imports.Rout.save
/usr/lib64/R/library/rpart.plot/slowtests/test.imports.bat
/usr/lib64/R/library/rpart.plot/slowtests/test.na.R
/usr/lib64/R/library/rpart.plot/slowtests/test.na.Rout.save
/usr/lib64/R/library/rpart.plot/slowtests/test.na.bat
/usr/lib64/R/library/rpart.plot/slowtests/test.palette.R
/usr/lib64/R/library/rpart.plot/slowtests/test.palette.Rout.save
/usr/lib64/R/library/rpart.plot/slowtests/test.palette.bat
/usr/lib64/R/library/rpart.plot/slowtests/test.prolog.R
/usr/lib64/R/library/rpart.plot/slowtests/test.rpart.plot.R
/usr/lib64/R/library/rpart.plot/slowtests/test.rpart.plot.Rout.save
/usr/lib64/R/library/rpart.plot/slowtests/test.rpart.plot.bat
/usr/lib64/R/library/rpart.plot/slowtests/test.rpart.rules.R
/usr/lib64/R/library/rpart.plot/slowtests/test.rpart.rules.Rout.save
/usr/lib64/R/library/rpart.plot/slowtests/test.rpart.rules.bat
/usr/lib64/R/library/rpart.plot/slowtests/test.type5.R
/usr/lib64/R/library/rpart.plot/slowtests/test.type5.Rout.save
/usr/lib64/R/library/rpart.plot/slowtests/test.type5.bat
/usr/lib64/R/library/rpart.plot/slowtests/usersplits.R
/usr/lib64/R/library/rpart.plot/slowtests/usersplits.Rout.save
/usr/lib64/R/library/rpart.plot/slowtests/usersplits.bat
/usr/lib64/R/library/rpart.plot/slowtests/vignette.R
/usr/lib64/R/library/rpart.plot/slowtests/vignette.Rout.save
/usr/lib64/R/library/rpart.plot/slowtests/vignette.bat
/usr/lib64/R/library/rpart.plot/slowtests/webpage.figs.R
/usr/lib64/R/library/rpart.plot/slowtests/webpage.figs.Rout.save
/usr/lib64/R/library/rpart.plot/slowtests/webpage.figs.bat
/usr/lib64/R/library/rpart.plot/tests/README.txt
/usr/lib64/R/library/rpart.plot/tests/test.rpart.plot.R
/usr/lib64/R/library/rpart.plot/tests/test.rpart.plot.Rout.save
